name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Build LatinaSub-Go
        run: go build -o ./latinasub ./cmd/latinasub/main.go

      - name: Run LatinaSub-Go
        env:
          CONCURRENT: 200
        run: ./latinasub save_to_db
